<a href="https://colab.research.google.com/github/Ridzzz0Alam/Data_Science/blob/main/Assignment_on_Module_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

In [ ]:
# Please consult the lectures
"""
A vector is a 1-D array single row or single column.
A matrix is a 2-D array with rows and column
"""

**2. How to import `NumPy` library?**

In [ ]:
# To avoid overwriting the output, please code here

In [1]:
import numpy as np

**3. Convert the given Python list into NumPy array and check its data type**

In [2]:
list_1 = [1,2,3,4,5]

In [ ]:
# To avoid overwriting the output, please code here

In [3]:
arr=np.array(list_1)
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int64


**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [ ]:
# To avoid overwriting the output, please code here

In [5]:
np.arange(0,6)

array([0, 1, 2, 3, 4, 5])

**5. Generate an `array of "5" zeros` **

In [6]:
# To avoid overwriting the output, please code here

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

**6. Generate the following `matrix`.**

In [7]:
# To avoid overwriting the output, please code here

In [9]:
np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [ ]:
# To avoid overwriting the output, please code here

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

**8. Generate an array of "5" tens.**

In [ ]:
# To avoid overwriting the output, please code here

In [11]:
np.ones(5)*10

array([10., 10., 10., 10., 10.])

**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [ ]:
# To avoid overwriting the output, please code here

In [13]:
np.arange(52,100,2)

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [ ]:
# To avoid overwriting the output, please code here

In [14]:
arr,step=np.linspace(0,1,10,retstep=True)
print(arr)
print(step)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
0.1111111111111111


**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [ ]:
# To avoid overwriting the output, please code here

In [15]:
# Generating vector array
vec=np.arange(25)
print(vec)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [ ]:
# To avoid overwriting the output, please code here

In [16]:
# reshape to convert into 2-d
mat=vec.reshape(5,5)
print(mat)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
# To avoid overwriting the output, please code here

In [17]:
# Using shape
vec.shape=(5,5)
print(vec)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


**12. Please generate the following matrix.**

In [ ]:
# To avoid overwriting the output, please code here

In [18]:
np.arange(1,17).reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [ ]:
# To avoid overwriting the output, please code here

In [19]:
print(np.linspace(0,5,10))

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


**14. What is the main difference between `linspace()` and `arange()`?**

In [ ]:
# Please consult the lectures.
# arange() takes 3rd argument as step size.
# linspace() take 3rd argument as no of point we want.
"""
arrange() uses setp size
linspace() uses number of points
"""

**15. How to generate a single random integer number using NumPy built-in function?**

In [ ]:
# To avoid overwriting the output, please code here

In [21]:
np.random.randint(1,100)

92

**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [ ]:
# To avoid overwriting the output, please code here

In [22]:
np.random.rand(7,5)

array([[0.44565483, 0.68081727, 0.88693036, 0.55463255, 0.39122074],
       [0.15675323, 0.09590424, 0.95179808, 0.21750832, 0.4610734 ],
       [0.94626039, 0.93834376, 0.74868516, 0.17887399, 0.81063257],
       [0.2577787 , 0.66765564, 0.01433626, 0.88675369, 0.73600842],
       [0.79254105, 0.76919012, 0.72990809, 0.5110805 , 0.54615562],
       [0.85616647, 0.63873061, 0.09706937, 0.60738917, 0.25517627],
       [0.26841656, 0.65283335, 0.36919463, 0.8793057 , 0.93305513]])

**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [ ]:
# To avoid overwriting the output, please code here

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck